### ISSUE TITLE
Provide simplified access to custom log levels

### ISSUE THREAD

**Issue by PFython** [PFython/log2d#1]
I'm not sure what the most convenient syntax for this might be, but a common requirement is to change the standard log levels.  Since log2d is intended as a simple but powerful wrapper around the complexities of logging, it would be a nice enhancement to offer this too.

**Comment by MikeDP** [comment]
Just been looking to **ADD**  "SUCCESS" and "TRACE" as new levels but it looks like you need to do this via the underlying _logging_ module _before_ instantiating a log2d.Log object.  It would be great to be able to do this simply from within a log2d.Log instance, without explicitly touching _logging_.

I've been using [loguru](https://github.com/Delgan/loguru) but log2d is **_much_** simpler/better for me and I'm replacing it.  However, loguru does seem to have non-standard levels but it's not yet clear how without digging a bit more.

**Comment by MikeDP** [comment]
Well, that went better than I expected :)

Although clearly not directly within log2d.Log, you can achieve this as follows.  In the module where you want to use log2d:
- Import logging, then log2d
- Before using log2d, set up the new levels in logging
- Now they are available in log2d

Code as follows seems to work:
```
import logging
from log2d import Log
...
# Add SUCCESS logging level
SUCCESS = 25    # INFO = 20, WARNING = 30
logging.addLevelName(SUCCESS, 'SUCCESS')

def success(self, message, *args, **kws):
    """ Test method for SUCCESS levels"""
    self.log(SUCCESS, message, *args, **kws)

logging.Logger.success = success

# Add TRACE logging level
TRACE = 15    # INFO = 20, DEBUG = 10
logging.addLevelName(TRACE, 'TRACE')

def trace(self, message, *args, **kws):
    """ Test method for TRACE levels"""
    self.log(TRACE, message, *args, **kws)
...
Mylog = LOG("SUMMARY", to_file=True).logger
...
Mylog.trace("This message level is TRACE")
```
This seems to work as expected, though, as yet,  I'm unsure of any impact this approach will have on logging.  I need to read some more

**Comment by PFython** [comment]
Thanks for the encouraging words and suggested code Mike... This has spurred me on and I'd like to suggest the following alternative based on your approach:

```
from log2d import Log, logging

mylog = Log("mylog").logger
mylog.debug("Debugging message...")
logging.SUCCESS = 25  # between WARNING and INFO
logging.addLevelName(logging.SUCCESS, 'SUCCESS')
setattr(mylog, 'success', lambda message, *args: mylog._log(logging.SUCCESS, message, args))
mylog.success("Success message...")
```
I don't propose to cover every possible edge case but this seems to work nicely and I'll aim to add this into the next release so you can just call `.add_level()`

**Comment by PFython** [comment]
Hi again Mike... I've now incorporated this in a new branch ("add_level") and published it on test.pypi:

`pip install -i https://test.pypi.org/simple/ log2d==0.0.17`

Would you be kind enough to have a play and let me know if you find any problems please?

Here's the relevant section of the updated README:

> ```
> from log2d import Log, logging
> 
> mylog = Log("mylog")
> 
> mylog.add_level("NewError", below="ERROR")
> mylog.add_level("NewInfo", above="INFO")
> 
> Log.mylog.newerror(f"New log level {logging.NEWERROR} below ERROR")
> Log.mylog.newinfo(f"New log level {logging.NEWINFO} above INFO ")
> 
> Output:
> "New log level 'newerror' added with value: 39"
> "New log level 'newinfo' added with value: 21"
> mylog|NEWERROR|2022-11-09T06:17:00+0000|New log level 39 below ERROR
> mylog|NEWINFO |2022-11-09T06:17:17+0000|New log level 21 above INFO
> ```
> 
> This method returns a confirmation message rather than logging its own output and potentially messing up your pristine logging schema.  You can suppress it by assigning a dummy variable e.g.
> 
> ```
> _ = mylog.add_level("NewError", below="ERROR")
> ```
> 
> `.add_level()` will also overwrite previous log levels at a given value if they already exist, and create the new log level _immediately_ above or below the reference log level i.e. without leaving any gaps.  For explicit control over the postion of log levels, you can also specify the log level value numerically:
> 
> ```
> mylog.add_level("TRACE", 15)
> Log.mylog.trace("Trace message...")
> ```

**Comment by MikeDP** [comment]
Brilliant!  It will take me a few days to check this out and I'll get back to you.

FYI, I'm using this as part of a centralised UDP broadcast logging/alerting system for all my home machines. The broadcast messages are simple json strings, so I can log from python, bash etc.

**Comment by MikeDP** [comment]
Hi Peter,

I'm going through it and so far all I've noted are the following:
 - You can overwrite an existing level value: this _may_ be possible in logging, I haven't checked.
 - You can set level value to e.g. -10, but again, this may be allowed by logging
 - If you e.g. add_level("success", above=info) then setLevel("CRITICAL") the "SUCCESS" messages still go into the log - they are not dropped as are e.g "ERROR" messages.
 I'll let you know if I see anything else.

FYI: Python 3.8.10 on Linux Mint 20.3

**Comment by PFython** [comment]
That's great feedback thanks Mike!

The first two points I think I'll probably handle with a simple warning in the README... the positioning of `log2d` is really for people who don't want or need to go into the "guts" of the main logging module.  So if they're at the point of setting explicit values then I think it's for them to do the research and avoid the pitfalls themselves.

The 3rd point is definitely an issue, thanks for spotting that.  I'll have to look at that again, but please let me know if you work out a fix before me?

Please keep 'em coming :)

**Comment by PFython** [comment]
Actually Mike what would be super helpful is if you could give me a 2-3 line TEST for point #3 which is currently failing please?  I can then add that to the tests for future, and also be 100% sure we're talking about the same thing.

**Comment by MikeDP** [comment]
OK, here's a simple bit that should do it.  Just uncomment the setLevel line to see the effect.
```
def testEvent1(Msg: str) -> bool:
    '''Test as designed.  Add two new EVENTS'''
    
    LG = Log(_Log, path=_HPath)  # _Log = "testlog", _HPath = os.path.join(os.environ['HOME'], '.logs')

    print(LG.add_level("Success", above="INFO"))
    print(LG.add_level("Fail", above="SUCCESS"))

    #LG.logger.setLevel('CRITICAL')

    LG.logger.success(f"{Msg}: Success!")
    LG.logger.info(f"{Msg}: 'Info'")
    LG.logger.fail(f"{Msg}: Fail!")`

```
Same result if we use LG.testlog.success(Msg) or getattr(LG, _Log).success(Msg)

**Comment by MikeDP** [comment]
Hi Peter,

I think I've found it.  Logging.addlevel examples I've found have a test of the message level in the function - "isEnabledFor(LVL)".  So, you may need something like:

`setattr(self.logger, lower_name, lambda message, *args: self.logger._log(level_value, message, args) if self.logger.isEnabledFor(level_value))`

Still looking for other issues but tragically short of time I'm afraid.  Nothing else so far :)

**Comment by MikeDP** [comment]
Hi Peter,

Oops! Slight issue with the above, but this one seems to work OK.
```
_Fn = lambda message, *args: self.logger._log(level_value, message, args) if self.logger.isEnabledFor(level_value) else None
setattr(self.logger, lower_name, _Fn)
```
Without the `else None` , you get a syntax error - lambdas must _always_ return something.

**Comment by PFython** [comment]
Much appreciated Mike - I'll have a look over the next few days hopefully!

**Comment by PFython** [comment]
Thanks for your patience Mike.  I added a slightly modified test and in the end merely had to add `if self.logger.isEnabledFor(level_value)` to my `add_level()` method.

Really appreciate your help.  I'll update on PyPI presently so you can enjoy the fruits of your labour!

**Comment by MikeDP** [comment]
Hi Peter, that's great.  Sorry I was not quick enough with these comments.  I very nearly sent them yesterday but ran out of time :(

OK, I've spent a little more time with this and I've also created a "find" log search function (see final comment below).  I've found nothing significant that doesn't stem from logging itself. :)

A couple of comments and points.  Note: it's clear some of these issues exist in logging itself so you may feel it's best not to address them.  However, if log2d is logging for the "less involved", maybe they are worth a look.

1.  add_level should just return a tuple or list of e.g ("SUCCESS", "success", 21), that is, the level as it appears in the log, the attribute name and the level value.  This may be of greater importance for non-English speakers - more below.
2.  Is it worth changing the __call__ convenience method to accept an optional level (default is existing Effectivelevel).  This would simplify all log message submissions.
3. There are localisation issues with add_level - primarily caused by using upper() and lower(). This is easiest to show with an example:
  ```
>>> A="groß"  # lower case eszett
  >>> print(A, A.upper(), A.lower(), A.casefold())      #  groß GROSS groß gross

  >>> A="GROẞ"  #  uppercase eszett
  >>> print(A, A.upper(), A.lower(), A.casefold())      #  GROẞ GROẞ groß gross

```
  Localisation and UTF-8 character sets are always a can of worms, so not sure what you can/should do about this but it does make it more important that the user knows exactly what level has been added,  particularly if the attribute get mangled, hence item 1 above.
  4.  FYI: If you add "NEWLEVEL" with a value of 20 (i.e. existing INFO), when you try to add an INFO message, you get a NEWLEVEL message. This looks like a _feature_ of logging so I suspect there's nothing you can do.

Finally, I've written a log search function which I'm just tidying and then Ill add it to the search issue.

**Comment by PFython** [comment]
Excellent comments thanks Mike, and the new find method looks great too!  I'm happy to incorporate these myself over the next week or so, or if you prefer you can Fork the repo, make your changes, and submit a Pull request... that way you'll appear forever as a "Contributor" on Github and get some well deserved credit :)

**Comment by MikeDP** [comment]
Hi Peter,
Thanks for your encouragement, I've not done this before but  I'll give
fork and pull a in try.  I've always felt I should give something back and
this is a good opportunity. Please bear with me.
