### ISSUE TITLE
Add convenience methods for extracting date range

### ISSUE THREAD

**Issue by PFython** [PFython/log2d#3]
A very common requirement is to extract just those rows before or after a certain timestamp.

Add convenience methods e.g. Log.from_dt and Log.to_dt to create a new log file and/or return string for further parsing.

Create a further method for removing unnecessary info based on known datetime format e.g. Log.remove_dt

**Comment by MikeDP** [comment]
Hi Peter, 
I've got an example of this working with log2d.  I'm just testing and then I can submit it if it looks like what you envisioned.  Here's the declaration:
```
    def find(self, text: str="", logname=None, date=None, deltadays: int=-7,
             level: str='NOTSET', separator: str="|",
             ignorecase: bool=True, autoparse: bool=False):
        """ Search log for:
               text:        text to seach for. Default '' means return everything
               logname:     path/to/another/log.log to search. Default=None, search this log
               date:        Date(time) object anchor for search. Default None = NOW
               deltadays:   number of days prior to (-ve) or after date. Default 1 week prior
               level:       log level below which results are ignored. Default NOTSET
               separator:   field separator character in log record. Default |
               ignorecase:  set case insensitivity. Default True
               autoparse:   if True, parses the log to find separator, time and level fields. 
                            If False, looks at log2d fmt string.  Default False
            Returns [MSG, ...] or []
        """


```

**Comment by PFython** [comment]
Nice work Mike thank you, and it was effortless in Github reviewing it and merging it.  I'll do a bit of testing myself then update PyPI.  Thanks again and congratulations on your (first?) successful Pull Request!
