### ISSUE TITLE
Possibly a nice typo in the __init__

### ISSUE THREAD

**Issue by MatusGasparik** [PFython/log2d#4]
https://github.com/PFython/log2d/blob/de42d65877646a85fe3bef77e0fd86de2ba3fef7/log2d/__init__.py#L39-L41

isn’t “keyword” meant to be “key”?

**Comment by chrisRedwine** [comment]
@MatusGasparik the version of the code on GitHub isn't even the same as the actual version from PyPI 😬...
```python
from inspect import getsource
from log2d import Log

print(next(filter(lambda l: "setattr" in l, getsource(Log).splitlines()), None))
```
```
'            setattr(self, key, value)'
```

**Comment by PFython** [comment]
Thanks - synced now.

**Comment by MatusGasparik** [comment]
Oops. Did I title this a „nice typo“??? Definitely a result of doing this on iPhone mini with a help from an intelligent text assistant…
