### ISSUE TITLE
UDPHandler?

### ISSUE THREAD

**Issue by MikeDP** [PFython/log2d#8]
Hi Peter,
For my own use, I added a udp handler so I can send messages to a UDP listener.  It uses json to pickle the log record so it _should_ be safer and lighter (though maybe less flexible) than the standard `logging.handlers.DatagranHandler` which uses pickle.

Any interest?

Mike

**Comment by PFython** [comment]
Hi Mike - sounds very interesting!  I think it's a little too niche for main package but if you've created a Fork with the UDP feature I think that would be a good place to maintain it... and I'd be really interested to see what you've done.

I'm a bit slow (sorry) but noticed a couple of minor things with the .find() method.  If I raise them as issues and suggest the tests that need to PASS, would you be kind enough to have another look at some point please?  No rush... but would be nice to get this 100% right (including my final tweaks to the README) before updating on PyPI.

All the best and thanks again for your enthusiasm and contributions!

**Comment by MikeDP** [comment]
Sure Peter. Something to do while the mince pies digest over the next couple of weeks :)

Open the issues and I'll take a look.

**Comment by PFython** [comment]
Hehe I think we both know those mince pies NEVER fully digest!!!

I've add a few issue now Mike - didn't have permission to assign them directly to you though.  I've made quite a lot of changes in the latest Merged Pull Request, both to the tests and to the variable names in the .find method.

Good luck, and I hope I haven't muddied the waters too badly...

**Comment by PFython** [comment]
PS strongly suggest you create your own fork from the latest version, then a new branch for each of the issues.  Then merge each branch back into your fork, and finally submit a Pull request to get those changes into my Master repository.  Hope that makes sense!

**Comment by MikeDP** [comment]
OK. Sorry should have commented here earlier perhaps.  Done and pull request submitted. :)
